# Generated by Django 4.0.3 on 2022-03-05 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('giveaways', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveaway',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='giveaways', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='giveaway',
            name='regions',
            field=models.ManyToManyField(related_name='giveaways', to='regions.region'),
        ),
        migrations.AddField(
            model_name='giveaway',
            name='watcher_list',
            field=models.ManyToManyField(blank=True, related_name='giveaway', to=settings.AUTH_USER_MODEL),
        ),
    ]
