# Generated by Django 4.0.3 on 2022-03-04 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('giveaways', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='giveaway',
            name='watcher_list',
            field=models.ManyToManyField(blank=True, related_name='giveaway', to=settings.AUTH_USER_MODEL),
        ),
    ]
