# Generated by Django 4.0.3 on 2022-03-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveaway',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='giveaway_link',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
