# Generated by Django 4.0.3 on 2022-03-09 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0003_alter_giveaway_description_alter_giveaway_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giveaway',
            old_name='watcher_list',
            new_name='watchlist',
        ),
    ]
