# Generated by Django 4.0.3 on 2022-03-09 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0004_rename_watcher_list_giveaway_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giveaway',
            name='watchlist',
        ),
    ]
