# Generated by Django 4.0.3 on 2022-03-09 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('giveaways', '0005_remove_giveaway_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveaway',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='giveaway', to=settings.AUTH_USER_MODEL),
        ),
    ]
