# Generated by Django 4.0.3 on 2022-03-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
        ('giveaways', '0002_initial'),
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ManyToManyField(related_name='jwt_auth', to='regions.region'),
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='jwt_auth', to='giveaways.giveaway'),
        ),
    ]
