# Generated by Django 4.0.3 on 2022-03-03 16:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_alter_user_socials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='socials',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), null=True, size=None),
        ),
    ]
