# Generated by Django 4.0.3 on 2022-03-09 11:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_alter_user_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='jwt_auth', to=settings.AUTH_USER_MODEL),
        ),
    ]
