# Generated by Django 4.0.3 on 2022-03-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0004_rename_watcher_list_giveaway_watchlist'),
        ('jwt_auth', '0003_alter_user_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='jwt_auth', to='giveaways.giveaway'),
        ),
    ]
