# Generated by Django 4.0.3 on 2022-03-03 17:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_alter_user_socials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='socials',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), blank=True, null=True, size=None),
        ),
    ]
