# Generated by Django 4.0.3 on 2022-03-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0001_initial'),
        ('jwt_auth', '0005_alter_user_socials'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wachlist',
            field=models.ManyToManyField(related_name='jwt_auth', to='giveaways.giveaway'),
        ),
    ]
