# Generated by Django 4.0.3 on 2022-03-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0001_initial'),
        ('jwt_auth', '0006_user_wachlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wachlist',
            field=models.ManyToManyField(blank=True, related_name='jwt_auth', to='giveaways.giveaway'),
        ),
    ]
