# Generated by Django 4.0.3 on 2022-03-03 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0007_alter_user_wachlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='wachlist',
            new_name='watchlist',
        ),
    ]
