# Generated by Django 4.0.3 on 2022-03-05 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('giveaways', '0001_initial'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='giveaway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='giveaways.giveaway'),
        ),
    ]
