# Generated by Django 4.0.3 on 2022-03-04 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_comment_replied_to_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replied_to_comment_id',
            field=models.ForeignKey(blank=True, default='0', on_delete=django.db.models.deletion.CASCADE, to='comments.comment'),
        ),
    ]
